name: Benchmark

on:
  push:
    branches:
      - 'main'

  # Run benchmarking for any PRs that target 'main' when they are opened or updated.
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd /tmp && wget https://releases.hashicorp.com/nomad/1.5.3/nomad_1.5.3_linux_amd64.zip && unzip nomad_1.5.3_linux_amd64.zip && chmod +x nomad && sudo mv nomad /usr/bin/
      - run: echo "# Benchmarks" >> ${GITHUB_STEP_SUMMARY}
      - run: cd .github/ci/benchmark && ./orchestrate.sh 3 m6id.xlarge ${GITHUB_SHA} >> ${GITHUB_STEP_SUMMARY}
        env:
          NOMAD_ADDR: https://ci.arewe1mtpsyet.com
          NOMAD_HTTP_AUTH: ${{ secrets.NOMAD_BENCHMARK_HTTP_AUTH }}
